export default [
  {
    key: '1',
    sender: 'ユーザー１',
    content:
      'イベント１です。イベント１です。イベント１です。イベント１です。イベント１です。イベント１です。',
    date: '8/10 20:00',
    imageUrl: '',
  },
  {
    key: '2',
    sender: '主催者',
    content: 'こんにちはああああああああ',
    date: '8/10 20:00',
    imageUrl: '',
  },
  {
    key: '3',
    sender: 'まいど',
    content:
      'まいどまいどまいどまいどまいどまいどまいどまいどまいどまいどまいどまいどまいどまいど',
    date: '8/10 20:00',
    imageUrl: '',
  },
  {
    key: '4',
    sender: 'サンプルユーザー',
    content: 'サンプルデータ',
    date: '8/10 20:00',
    imageUrl: '',
  },
  {
    key: '5',
    sender: 'テストユーザー',
    content: '内容です。内容です。内容です。内容です。内容です。',
    date: '8/10 20:00',
    imageUrl: '',
  },
  {
    key: '6',
    sender: 'テストユーザー',
    content: '内容です。内容です。内容です。内容です。内容です。',
    date: '8/10 20:00',
    imageUrl: '',
  },
  {
    key: '7',
    sender: 'テストユーザー',
    content: '内容です。内容です。内容です。内容です。内容です。',
    date: '8/10 20:00',
    imageUrl: '',
  },
  {
    key: '8',
    sender: 'テストユーザー',
    content: '内容です。内容です。内容です。内容です。内容です。',
    date: '8/10 20:00',
    imageUrl: '',
  },
  {
    key: '9',
    sender: 'テストユーザー',
    content: '内容です。内容です。内容です。内容です。内容です。',
    date: '8/10 20:00',
    imageUrl: '',
  },
  {
    key: '10',
    sender: 'テストユーザー',
    content: '内容です。内容です。内容です。内容です。内容です。',
    date: '8/10 20:00',
    imageUrl: '',
  },
  {
    key: '11',
    sender: 'テストユーザー',
    content: '内容です。内容です。内容です。内容です。内容です。',
    date: '8/10 20:00',
    imageUrl: '',
  },
  {
    key: '12',
    sender: 'テストユーザー',
    content: '内容です。内容です。内容です。内容です。内容です。',
    date: '8/10 20:00',
    imageUrl: '',
  },
];
